;==============================================================================
; Title:        Binary Coded Decimal (BCD) Fixed Point Math Functions.
; Sub-Title:    Trigonometry - Includes.
; Filename:     bcdfix-i-trig.inc
; Platform:     65XX CPU
; Language:     65XX Assembly Language (https://cc65.github.io/doc/ca65.html)
; Author:       Justin Lane (cpu65xx@jigglesoft.co.uk)
; Date:         2022-09-07 21:00
; Version:      0.0.6
;------------------------------------------------------------------------------
; Copyright (c) 2022 Justin Lane
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.
;------------------------------------------------------------------------------

;------------------------------------------------------------------------------
; INCLUDES.
;------------------------------------------------------------------------------

            ; Trigonometry - Constants.
            .INCLUDE    "bcdfix-i-trig-1.inc"
            ; Trigonometry - Angle Conversions.
            .INCLUDE    "bcdfix-i-trig-2.inc"
            ; Trigonometry - Sine, Cosine, Tangent.
            .INCLUDE    "bcdfix-i-trig-3.inc"
            ; Trigonometry - Arcsine, Arccosine, Arctangent.
            .INCLUDE    "bcdfix-i-trig-4.inc"
            ; Trigonometry - Cosecant, Secant, Cotangent.
            .INCLUDE    "bcdfix-i-trig-5.inc"
            ; Trigonometry - Arccosecant, Arcsecant, Arccotangent.
            .INCLUDE    "bcdfix-i-trig-6.inc"
            ; Trigonometry - Hyperbolic Sine, Hyperbolic Cosine, Hyperbolic Tangent.
            .INCLUDE    "bcdfix-i-trig-7.inc"
            ; Trigonometry - Area Hyperbolic Sine, Area Hyperbolic Cosine, Area Hyperbolic Tangent.
            .INCLUDE    "bcdfix-i-trig-8.inc"
            ; Trigonometry - Hyperbolic Cosecant, Hyperbolic Secant, Hyperbolic Cotangent.
            .INCLUDE    "bcdfix-i-trig-9.inc"
            ; Trigonometry - Area Hyperbolic Cosecant, Area Hyperbolic Secant, Area Hyperbolic Cotangent.
            .INCLUDE    "bcdfix-i-trig-a.inc"
            ; Trigonometry - TAN2, ATAN2
            .INCLUDE    "bcdfix-i-trig-b.inc"



;------------------------------------------------------------------------------


