;==============================================================================
; Title:        Binary Coded Decimal (BCD) Fixed Point Math Functions.
; Sub-Title:    Trigonometry - Arcsine, Arccosine, Arctangent.
; Filename:     bcdfix-i-trig-4.inc
; Platform:     65XX CPU
; Language:     65XX Assembly Language (https://cc65.github.io/doc/ca65.html)
; Author:       Justin Lane (cpu65xx@jigglesoft.co.uk)
; Date:         2022-09-07 21:00
; Version:      0.0.6
;------------------------------------------------------------------------------
; Copyright (c) 2022 Justin Lane
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.
;------------------------------------------------------------------------------


;------------------------------------------------------------------------------
; TRIGONOMETRY - ARCSINE, ARCCOSINE, ARCTANGENT.
;------------------------------------------------------------------------------

;TODO: PLACEHOLDER.



;------------------------------------------------------------------------------


